Module: LambdaRobots.HotShotRobot
Description: Robot focused on taking its targets down as quickly as possible
Items:

  - Function: RobotFunction
    Memory: 256
    Timeout: 30

  - Resource: RobotInvocationPermission
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref RobotFunction
      Principal: "*"

  - Variable: RobotArn
    Description: Lambda function ARN
    Scope: public
    Value: !GetAtt RobotFunction.Arn

  - Resource: RobotStateTable
    Description: Table for holding the state of the robot
    Scope: all
    Type: AWS::DynamoDB::Table
    Allow: ReadWrite
    Scope: all
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: Expire
        Enabled: true


