Module: LambdaRobots.BringYourOwnBot
Description: Build your own Lambda-Robot
Version: 1.0-DEV
Items:

  - Function: BotFunction
    Memory: 256
    Timeout: 30
    Properties:
      Environment:
        Variables:
          DEBUG_LOGGING_ENABLED: true

  - Resource: BotInvocationPermission
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref BotFunction
      Principal: "*"

  - Variable: BotArn
    Description: Lambda function ARN
    Scope: public
    Value: !GetAtt BotFunction.Arn
