Module: Challenge.LambdaRobots.Robot
Version: 1.0-DEV
Items:

  - Parameter: RobotName
    Scope: RobotFunction
    Section: Robot Settings
    Label: Name of robot

  - Parameter: AwsAccountId
    Section: Robot Settings
    Label: Optional AWS account ID to allow robot lambda bo be invoked from another account (leave empty to disable cross-account invocations)

  - Function: RobotFunction
    Memory: 256
    Timeout: 30

  - Resource: RobotInvocationPermission
    If: !Not [ !Equals [ !Ref AwsAccountId, "" ]]
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref RobotFunction
      Principal: !Ref AwsAccountId

  - Variable: RobotArn
    Description: Lambda function ARN
    Scope: public
    Value: !GetAtt RobotFunction.Arn

