Module: LambdaRobots.BringYourOwnRobot
Description: Build your own Lambda-Robot
Version: 1.0-DEV
Items:

  - Function: RobotFunction
    Memory: 256
    Timeout: 30

  - Resource: RobotInvocationPermission
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref RobotFunction
      Principal: "*"

  - Variable: RobotArn
    Description: Lambda function ARN
    Scope: public
    Value: !GetAtt RobotFunction.Arn
