Module: LambdaRobots.YosemiteSamRobot
Description: Robot that runs around randomly firing missiles in all directions
Items:

  - Function: RobotFunction
    Memory: 256
    Timeout: 30

  - Resource: RobotInvocationPermission
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref RobotFunction
      Principal: "*"

  - Variable: RobotArn
    Description: Lambda function ARN
    Scope: public
    Value: !GetAtt RobotFunction.Arn
